#!/usr/bin/env python3
"""Turn GUI2-owned SVG files into LVGL image descriptors."""

import re
import sys
from pathlib import Path


def cpp_name(path: Path) -> str:
    return "kGui2Icon" + "".join(part.capitalize() for part in path.stem[3:].split("_"))


def cpp_string(data: str) -> str:
    lines = []
    for line in data.splitlines(True):
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        if escaped.endswith("\n"):
            escaped = escaped[:-1] + "\\n"
        lines.append('"' + escaped + '"')
    return "\n".join(lines) if lines else '""'


def dimensions(data: str) -> tuple[int, int]:
    match = re.search(r"<svg\s[^>]*\bwidth=\"(\d+)\"[^>]*\bheight=\"(\d+)\"", data)
    if match is None:
        raise ValueError("SVG must have integer width and height")
    return int(match.group(1)), int(match.group(2))


def main() -> None:
    print("// Generated by generate_svg_header.py. Do not edit.")
    print("#pragma once")
    print()
    for argument in sys.argv[1:]:
        path = Path(argument)
        data = path.read_text(encoding="utf-8")
        width, height = dimensions(data)
        name = cpp_name(path)
        svg_name = name + "Svg"
        print(f"static constexpr char {svg_name}[] =")
        print(cpp_string(data) + ";")
        print(f"static constexpr unsigned int {svg_name}Size = sizeof({svg_name}) - 1;")
        print(f"static const lv_image_dsc_t {name} = {{")
        print("  .header = { .magic = LV_IMAGE_HEADER_MAGIC,")
        print("              .cf = LV_COLOR_FORMAT_ARGB8888,")
        print("              .flags = 0,")
        print(f"              .w = {width}, .h = {height},")
        print(f"              .stride = {width} * 4, .reserved_2 = 0 }},")
        print(f"  .data_size = {svg_name}Size,")
        print(f"  .data = reinterpret_cast<const uint8_t*>({svg_name}),")
        print("  .reserved = nullptr, .reserved_2 = nullptr,")
        print("};")
        print()


if __name__ == "__main__":
    main()
